# https://hub.docker.com/r/library/node/tags/
# Using the node alpine image to build the React app
image: php:7.3-fpm-alpine

# Announce the URL as per CRA docs
# https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#advanced-configuration

variables:
  # AWS access keys stored as secret variables
  # AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  # AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

  BUILD_DIR: build
  # development | production | testing
  DEPLOY_TARGET: development

# Composer stores all downloaded packages in the vendor/ directory.
# Do not use the following if the vendor/ directory is committed to your git repository.
# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - vendor/

# Name the stages involved in the pipeline
stages:
  - test
  - deploy

before_script:
  # Install composer dependencies
  - curl -o installer.sig https://composer.github.io/installer.sig
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php'); unlink('installer.sig');"
  - mv composer.phar /usr/local/bin/composer
  - composer install

# Job name for gitlab to recognise this results in assets for Gitlab Pages
# https://docs.gitlab.com/ee/user/project/pages/introduction.html#gitlab-pages-requirements

test:
  stage: test
  script:
    - echo "test"

deploy-staging:
  stage: deploy
  variables:
    DEPLOY_TARGET: development
  only:
    - develop
    - /^v(.+)-staging$/
  script:
    - echo "deploy-staging"
    - php -v
    - composer --version
    - echo "end deploy-staging"

deploy-production:
  stage: deploy
  variables:
    DEPLOY_TARGET: production
  only:
    - master
    - /^v(.+)-stable$/
  script:
    - echo "deploy-production"
